Update README.md
JeffersonLab/hpstr pull request #70
Opened 2020-03-12 18:35 UTC by mccaky

Updated the README file to include a description of the bump hunter functionality, as requested.

2020-03-12 22:36 UTC, pbutti requested changes
Just fix typos. Description looks good. Thanks for this

2020-03-12 22:36 UTC, pbutti commented on README.md
> +hpstr also includes the HPS 2019 resoancne search analysis functionality. A brief description of the capabilities of this code, and how to use it, is included here.
typo -> resonance

2020-03-12 22:36 UTC, pbutti commented on README.md
> +   ${backgroundFitPolynomialOrder}: The resonance search uses background fit polynomials of the form 10^(T_n(m)), where T_n(m) is a Chebyshev polynomial of the first kind of order n. This argument sp
isn't it e^{} ? really 10^ ?

2020-03-12 22:36 UTC, pbutti commented on README.md
> +In addition to the above mentioned variables, it is also possible to sacle the mass resolution by an arbitrary float by adding the argument "-r ${scalingFactor}".
typo -> scale

2020-03-13 22:27 UTC, cbravo135 commented on README.md
> +   ${backgroundFitPolynomialOrder}: The resonance search uses background fit polynomials of the form 10^(T_n(m)), where T_n(m) is a Chebyshev polynomial of the first kind of order n. This argument sp
It really is 10^

2020-03-13 22:35 UTC, mccaky commented on README.md
> +hpstr also includes the HPS 2019 resoancne search analysis functionality. A brief description of the capabilities of this code, and how to use it, is included here.
This should be fixed now.

2020-03-13 22:35 UTC, mccaky commented on README.md
> +In addition to the above mentioned variables, it is also possible to sacle the mass resolution by an arbitrary float by adding the argument "-r ${scalingFactor}".
This should be fixed now, too.

2020-03-13 22:36 UTC, cbravo135 approved these changes

2020-03-13 22:37 UTC, mccaky commented
The two typos you pointed at should be fixed now. Let me know if anything else needs improvement.

2020-03-13 22:38 UTC, merged